//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TehServies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki
    {
        public int ID { get; set; }
        public int Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Oborudovaniye { get; set; }
        public int Crush { get; set; }
        public string Descr { get; set; }
        public int Client { get; set; }
        public int Status { get; set; }
        public int Otvetstvennii { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
        public virtual Crushes Crushes { get; set; }
        public virtual Oborudovaniye Oborudovaniye1 { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
